### ISSUE TITLE
Macのchromeでサンプルページが表示できない場合がある

### ISSUE THREAD

**Issue by takaesu-ug** [1pac/css-modules#12]
chrome結構使われているブラウザだと思うので、サンプルページ見れないのどうにかしたい。。。
以下のページにchromeでアクセスした場合、正常に見れない事が多い。たまにクラッシュする。
http://1pac.github.io/css-modules/sample/

**Comment by takaesu-ug** [comment]
この行が原因であることは突き止めました。
https://github.com/1pac/css-modules/blob/master/sample/js/sample.js#L19-L31
の処理の中で以下の部分で、 `append($template)` の箇所が影響しているようです。

```
$sample.append($template).find('._code').text($resource);
```

$templateには `$('<pre><code class="_code html"></code></pre>')` という内容が入っていますが、
以下のようにして `<pre>` タグを出力しないようにするとスタイルは崩れるけど表示はできます。

```
$sample.append($template.contents()).find('._code').text($resource);
```

対応策がこれ以上はわかりませんでした。。
ちなみにUnderscoreのテンプレートで展開して、appendするようにしても同じだったので、appendの部分に何かありそうです。

https://github.com/yusabana/css-modules/commit/d9ce099e6fbadc1a780385c005ab89190ce42b90

**Comment by volkuwabara** [comment]
@yusabana 
これ困ったな〜って思ってたんですよね。
検証ありがとうございます！
Firefoxではうまく動くのと、ChromeでもUnagiのころは問題なかったので、
Chromeがアップデートして仕様がかわった的な感じかなと思ってました。
(SPAではこのJS自体OFFられているようです。)

ちなみに
`pre` を入れないようにしたらすんなりサクサク動いたのでしょうか？？

**Comment by takaesu-ug** [comment]
@volkuwabara 
試しにpreタグを外したものでぼくのリポジトリで動かしてみました。
http://yusabana.github.io/css-modules/sample/index.html
さくさく見れるという点は、、、、ですが一応問題なく表示はできるんすよね。

変更点は以下です。
https://github.com/yusabana/css-modules/commit/c631f375c2937df3f39ede0312eb777a30555157

`pre` が悪いのか `code` が悪いのかのいずれかなのかもしれません。

**Comment by takaesu-ug** [comment]
さらに、、
codeタグではなく、preタグだけにしたものも作ってみました。

http://yusabana.github.io/css-modules/sample/index2.html

現時点では、
- http://yusabana.github.io/css-modules/sample/index.html は `code` タグのみ
- http://yusabana.github.io/css-modules/sample/index2.html は `pre` タグのみ

`pre` のみは `code` のみより遅いですね。(もしやCSSも影響している??）

**Comment by volkuwabara** [comment]
@yusabana 
あざす！
僕の環境だと、index2は動いてくれなかった〜
`code` タグのみの方に直してった方が近道な気がするね。
でも`code`を使うと重くなる原因がよく分からないなあ

http://yusabana.github.io/css-modules/sample/index.html をみると、コード内の改行が
ツメられてしまってたりするけどなんでだろう？

> preタグのみのものはcodeたぐのみより遅いですね。(もしやCSSも影響している??）

CSSが原因でこんなに重くなることはまずないですね〜
JSの処理がループになってしまっているとか、なんか再帰的にしくってるとか

**Comment by volkuwabara** [comment]
> 僕の環境だと、index2は動いてくれなかった〜

と思ったら結構遅れてロードされてたっす。
sample.js 自体は僕が浅はかなJSの知識で書いたやつなので、
そもそも文法的に間違ってるとかっていうのもあるかもしれません。

**Comment by takaesu-ug** [comment]
README.mdの、http://1pac.github.io/css-modules/sample/ のリンクの下にでも注意書きでchromeでは見ないで、FirefoxやsafariやIEで見てってのを一時的に入れておいたほうがいいかもっすねー

**Comment by volkuwabara** [comment]
@yusabana 
https://github.com/1pac/css-modules/pull/16
↑のコミットで対応してみました。

`pre`タグを使わないで、code タグに対して `white-space: pre;` を使うようにJS/CSSを修正しました。
それでもChromeでは改行コードの変換に時間がかかるのか、少しロードに時間がかかりますが、
クラッシュはしなくなりました。
他のブラウザでは問題なしです。
一応Readmeには、Chromeだとちょっと読み込み遅い旨書いてあります。

お手すきで確認ください〜
http://1pac.github.io/css-modules/sample/

**Comment by takaesu-ug** [comment]
chromeちょっと遅いけど、普通に見れるようになりました！！
クローズします。
